[package]
name = "commute-tracker-api"
version = "0.0.1"
authors = ["Chris Thorn <chris@thorn.co>"]

[dependencies.postgres]
version = "0.9"
features = ["time"]

[dependencies.time]
version = "0.1"

[dependencies.nickel]
version = "0.5"

[dependencies.rustc-serialize]
version = "0.3"
